- hosts: localhost
  tasks:
  - name: List older files
    find:
      paths: "/var/www/backup/versions/"
      age: "5d"
      age_stamp: atime
    register: older_than_5d

  - name: Remove files older than 5 days
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ older_than_5d.files }}"

  - name: Check that the backup exists
    stat:
      path: /var/www/backup/versions/wp-{{lookup('pipe', "date +%Y-%m-%d")}}.tgz
    register: stat_result

  - name: Archive folder
    archive:
      path: /var/www/html/wordpress/
      dest: /var/www/backup/versions/wp-{{lookup('pipe', "date +%Y-%m-%d")}}.tgz
    when: stat_result.stat.exists == False

  - name: Dump specific Database
    mysql_db:
      state: dump
      login_user: root
      login_password: passwd
      name: dbname
      target: /var/www/backup/versions/db-{{lookup('pipe', "date +%Y-%m-%d")}}.gz
